In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

In [2]:
recipes = pd.read_csv('foodcom_with_reviews/recipes.csv')
reviews = pd.read_csv('foodcom_with_reviews/reviews.csv')

In [3]:
recipes.head() #checking my dataset on recipes

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,3.8,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc..."
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",...,0.1,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil..."

In [4]:
reviews.head() #exploring a dataset

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z,2000-03-28T12:51:00Z

In [5]:
reviews.loc[(reviews['RecipeId'] == 992)] # exploring to see the reviews on a dish

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
166,250,992,4242,marie m,5,my family loved these. fresher than any bough...,2001-01-02T16:19:29Z,2001-01-02T16:19:29Z
226609,242612,992,205100,mommyoftwo,5,Wow! Awesome - Awesome - Awesome! And I don'...,2006-01-27T06:09:46Z,2006-01-27T06:09:46Z
430694,463486,992,559815,karen.nash-horton,4,This is a good recipe. I much prefer the oven ...,2007-08-15T11:04:13Z,2007-08-15T11:04:13Z
589936,643932,992,743849,NELady,5,"GREAT recipe! I used fat free cream cheese, p...",2008-06-02T18:24:08Z,2008-06-02T18:24:08Z
697696,768046,992,1072593,gailanng,5,Ay Karumba! I've made these for various socia...,2008-12-17T18:56:35Z,2008-12-17T18:56:35Z
811856,906390,992,145580,sue parenio,5,These are heaven (and thank you gail for the t...,2009-07-13T15:47:24Z,2009-07-13T15:47:24Z
817453,913294,992,1248818,Babbsy,5,My guests popped these in their mouths and the...,2009-07-24T20:56:16Z,2009-07-24T20:56:16Z
876552,992835,992,857489,bad kitty 1116,5,These are the best! They are so much better th...,2009-11-20T13:57:25Z,2009-11-20T13:57:25Z
917775,1049317,992,885673,tbeale20,5,I have been making this recipe for years. The...,2010-02-06T10:51:30Z,2010-02-06T10:51:30Z
918754,1050634,992,1505073,Peters Mom,5,These are much easier to prepare than I imagin...,2010-02-09T00:35:24Z,2010-02-09T00:35:24Z
1007383,1153499,992,178427,CJAY8248,5,Wonderful recipe!!! This is so easy and they t...,2010-10-11T02:47:46Z,2010-10-11T02:47:46Z

In [6]:
recipes.dtypes

RecipeId                        int64
Name                           object
AuthorId                        int64
AuthorName                     object
CookTime                       object
PrepTime                       object
TotalTime                      object
DatePublished                  object
Description                    object
Images                         object
RecipeCategory                 object
Keywords                       object
RecipeIngredientQuantities     object
RecipeIngredientParts          object
AggregatedRating              float64
ReviewCount                   float64
Calories                      float64
FatContent                    float64
SaturatedFatContent           float64
CholesterolContent            float64
SodiumContent                 float64
CarbohydrateContent           float64
FiberContent                  float64
SugarContent                  float64
ProteinContent                float64
RecipeServings                float64
RecipeYield                    object
RecipeInstructions             object
dtype: object

In [7]:
recipes.iloc[:,10:17]

,RecipeCategory,Keywords,RecipeIngredientQuantities,RecipeIngredientParts,AggregatedRating,ReviewCount,Calories
0,Frozen Desserts,"c(""Dessert"", ""Low Protein"", ""Low Cholesterol"",...","c(""4"", ""1/4"", ""1"", ""1"")","c(""blueberries"", ""granulated sugar"", ""vanilla ...",4.5,4.0,170.9
1,Chicken Breast,"c(""Chicken Thigh & Leg"", ""Chicken"", ""Poultry"",...","c(""1"", ""4"", ""2"", ""2"", ""8"", ""1/4"", ""8"", ""1/2"", ...","c(""saffron"", ""milk"", ""hot green chili peppers""...",3.0,1.0,1110.7
2,Beverages,"c(""Low Protein"", ""Low Cholesterol"", ""Healthy"",...","c(""1 1/2"", ""1"", NA, ""1 1/2"", NA, ""3/4"")","c(""sugar"", ""lemons, rind of"", ""lemon, zest of""...",4.5,10.0,311.1
3,Soy/Tofu,"c(""Beans"", ""Vegetable"", ""Low Cholesterol"", ""We...","c(""12"", ""1"", ""2"", ""1"", ""10"", ""1"", ""3"", ""2"", ""2...","c(""extra firm tofu"", ""eggplant"", ""zucchini"", ""...",4.5,2.0,536.1
4,Vegetable,"c(""Low Protein"", ""Vegan"", ""Low Cholesterol"", ""...","c(""46"", ""4"", ""1"", ""2"", ""1"")","c(""plain tomato juice"", ""cabbage"", ""onion"", ""c...",4.5,11.0,103.6
...,...,...,...,...,...,...,...
522512,Dessert,"""< 4 Hours""","c(""3"", ""1/2"", ""1/2"", ""1/4"", ""1/4"", ""1"", ""1/4"",...","c(""fresh ginger"", ""unsalted butter"", ""dark bro...",NaN,NaN,316.6
522513,Very Low Carbs,"c(""High Protein"", ""High In..."", ""< 4 Hours"")","c(""9"", ""2"", ""4"", ""2"", ""1/3"", ""3 1/2"", ""1/3"")","c(""Dijon mustard"", ""garlic"", ""peppercorns"", ""s...",NaN,NaN,2063.4
522514,Ice Cream,"c(""Dessert"", ""< 4 Hours"")","c(""3"", ""3"", ""1/2"", ""1/2"", ""2"", ""2"")","c(""half-and-half"", ""heavy cream"", ""brandy"", ""s...",NaN,NaN,1271.3
522515,Canadian,"c(""< 15 Mins"", ""Easy"")","c(""4"", ""1/4"", ""1"", ""1/2"", ""8 1/2"", ""40"")","c(""wasabi paste"", ""dill"", ""English cucumber"", ...",NaN,NaN,16.1
522516,Breakfast,"""< 60 Mins""","c(""6 -7"", ""1"", ""1/4"", ""1"", ""2"", ""1/2"", ""1"", ""1...","c(""hard-boiled eggs"", ""breakfast sausage"", ""pa...",NaN,NaN,1093.3

In [8]:
reviews.loc[(reviews['Rating'] < 3)] #just exploring the data

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z
7,21,148,2156,Darlene Blythe,0,Would someone please check the Nutrition Facts...,2000-06-02T10:01:00Z,2000-06-02T10:01:00Z
13,28,1451,2416,jessontanya,1,Where does the bbq come in,2000-08-01T19:17:30Z,2000-08-01T19:17:30Z
16,42,5466,2059,Moishe Lettvin 1,1,Dear lord.,2000-10-18T11:31:40Z,2000-10-18T11:31:40Z
34,73,2502,2848,Jeff Lucco,0,Unusual name for a recipe that has no pumpkin ...,2000-10-17T15:03:25Z,2000-10-17T15:03:25Z
...,...,...,...,...,...,...,...,...
1401962,2090322,498981,2002901277,Paul P.,0,Iâ€™ve been making theses for 5 years now. The o...,2020-12-27T16:13:19Z,2020-12-27T16:13:19Z
1401963,2090323,450339,2002901298,Karen G.,0,Wow! Love Paula Deen's recipes and this is no ...,2020-12-27T16:32:26Z,2020-12-27T16:32:26Z
1401968,2090329,103772,2002553884,Clare D.,2,The filling was quite bland before I tweaked i...,2020-12-27T18:50:54Z,2020-12-27T18:50:54Z
1401972,2090334,105865,2002901740,jessica92983,2,Iâ€™m not usually a big chili fan but wanted to ...,2020-12-27T23:04:59Z,2020-12-27T23:04:59Z
1401977,2090339,139499,2002080368,terrylbiggs,2,I was disappointed. I couldn't wait to make th...,2020-12-27T23:57:54Z,2020-12-27T23:57:54Z

In [9]:
reviews.loc[(reviews['Rating'] < 3)].shape # just checking if there are many negative reviews

(110404, 8)

In [10]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1401982 entries, 0 to 1401981
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReviewId       1401982 non-null  int64
 1   RecipeId       1401982 non-null  int64
 2   AuthorId       1401982 non-null  int64
 3   AuthorName     1401982 non-null  object
 4   Rating         1401982 non-null  int64
 5   Review         1401768 non-null  object
 6   DateSubmitted  1401982 non-null  object
 7   DateModified   1401982 non-null  object
dtypes: int64(4), object(4)
memory usage: 85.6+ MB

In [11]:
#repetition of reviewers id could help to recommend

In [12]:
recipes['RecipeInstructions'].str.contains('cheddar') #testing to search on the recipeinstruction

0         False
1         False
2         False
3         False
4         False
          ...
522512    False
522513    False
522514    False
522515    False
522516    False
Name: RecipeInstructions, Length: 522517, dtype: bool

In [13]:
recipes.loc[recipes['RecipeInstructions'].str.contains('cheddar')].head() #looking for columns that has this ingredient

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
115,162,Chicken Lasagna,1562,Libby1,PT2H,PT30M,PT2H30M,1999-09-20T19:42:00Z,Make and share this Chicken Lasagna recipe fro...,character(0),...,4.7,29.4,693.5,10.9,0.8,3.1,18.1,8.0,NaN,"c(""Mix filling ingredients in large bowl."", ""S..."
234,292,Curried Vegetables,1612,JANIC412,PT35M,PT30M,PT1H5M,1999-08-25T05:33:00Z,Make and share this Curried Vegetables recipe ...,character(0),...,6.1,27.5,869.0,21.6,3.1,5.6,6.4,6.0,NaN,"c(""Cook the cauliflower, carrots, celery, and ..."
244,302,Twice Baked Ham and Cheese Potatoes,1704,HELEN PEAGRAM_40951,PT1H30M,PT25M,PT1H55M,1999-09-15T03:57:00Z,Make and share this Twice Baked Ham and Cheese...,character(0),...,15.1,80.7,611.7,41.6,4.7,3.1,17.1,6.0,NaN,"c(""Bake potatoes at 400 degrees Fahrenheit for..."
353,422,Linda's Tuna Burritos,1575,lindaWWJD,PT1M,PT20M,PT21M,1999-08-21T11:20:00Z,Make and share this Linda's Tuna Burritos reci...,character(0),...,8.1,29.7,900.6,59.4,3.6,2.5,16.5,8.0,NaN,"c(""Mix together tuna, olives, onions, cheddar ..."
472,558,German Potato-Cheese Soup,1549,Dave5003,PT40M,PT30M,PT1H10M,1999-08-17T04:36:00Z,Make and share this German Potato-Cheese Soup ...,"""https://img.sndimg.com/food/image/upload/w_55...",...,9.7,45.8,775.8,24.2,2.7,5.6,14.3,12.0,NaN,"c(""Peel and prepare vegetables."", ""In a large ..."

In [32]:
user_input = input('put your ingridients, followed by a comma')
user_input

recipes.loc[recipes['RecipeInstructions'].str.contains(user_input)]
# works but only in specific order

put your ingridients, followed by a commacheddar

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
115,162,Chicken Lasagna,1562,Libby1,PT2H,PT30M,PT2H30M,1999-09-20T19:42:00Z,Make and share this Chicken Lasagna recipe fro...,character(0),...,4.7,29.4,693.5,10.9,0.8,3.1,18.1,8.0,NaN,"c(""Mix filling ingredients in large bowl."", ""S..."
234,292,Curried Vegetables,1612,JANIC412,PT35M,PT30M,PT1H5M,1999-08-25T05:33:00Z,Make and share this Curried Vegetables recipe ...,character(0),...,6.1,27.5,869.0,21.6,3.1,5.6,6.4,6.0,NaN,"c(""Cook the cauliflower, carrots, celery, and ..."
244,302,Twice Baked Ham and Cheese Potatoes,1704,HELEN PEAGRAM_40951,PT1H30M,PT25M,PT1H55M,1999-09-15T03:57:00Z,Make and share this Twice Baked Ham and Cheese...,character(0),...,15.1,80.7,611.7,41.6,4.7,3.1,17.1,6.0,NaN,"c(""Bake potatoes at 400 degrees Fahrenheit for..."
353,422,Linda's Tuna Burritos,1575,lindaWWJD,PT1M,PT20M,PT21M,1999-08-21T11:20:00Z,Make and share this Linda's Tuna Burritos reci...,character(0),...,8.1,29.7,900.6,59.4,3.6,2.5,16.5,8.0,NaN,"c(""Mix together tuna, olives, onions, cheddar ..."
472,558,German Potato-Cheese Soup,1549,Dave5003,PT40M,PT30M,PT1H10M,1999-08-17T04:36:00Z,Make and share this German Potato-Cheese Soup ...,"""https://img.sndimg.com/food/image/upload/w_55...",...,9.7,45.8,775.8,24.2,2.7,5.6,14.3,12.0,NaN,"c(""Peel and prepare vegetables."", ""In a large ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522153,541016,Not Your Average Tuna Noodle Casserole,2591002,Santa Ed,PT40M,PT20M,PT1H,2020-09-29T18:16:00Z,Make and share this Not Your Average Tuna Nood...,character(0),...,4.2,51.8,220.7,25.6,1.5,2.1,13.1,6.0,1 cup,"c(""Mix cream of chicken, mayonnaise and milk t..."
522223,541088,Mediterranean Tilapia,4769,Katrina Wynn,PT10M,PT10M,PT20M,2020-10-19T15:19:00Z,"Nutrition Facts\n1 fillet: 197 calories, 4g fa...",character(0),...,2.8,73.6,299.2,4.5,2.0,1.6,27.7,6.0,NaN,"c(""Preheat oven to 400Â°. Place fillets in a 15..."
522319,541184,Michelle's Cheesey Chicken Lasagna,2002460118,mmontgomery32,PT35M,PT20M,PT55M,2020-11-09T15:59:00Z,Make and share this Michelle's Cheesey Chicken...,character(0),...,11.5,116.0,738.4,3.7,0.0,2.6,39.0,6.0,NaN,"c(""1>Pre-heat the oven to 425 degrees F."", ""2>..."
522324,541189,Cheddar-Garlic Chicken Breast With Corn and Peas,2002848759,Kaci L.,PT50M,PT1H,PT1H50M,2020-11-09T16:10:00Z,Make and share this Cheddar-Garlic Chicken Bre...,character(0),...,22.2,167.2,1101.1,54.0,9.4,8.2,44.5,4.0,NaN,"c(""CHICKEN BREAST:"", ""Preheat oven to 350Â°F."",..."
522498,541365,Leftover Rice Casserole,1808377,escripps,PT30M,PT15M,PT45M,2020-12-21T16:18:00Z,Make and share this Leftover Rice Casserole re...,character(0),...,16.5,79.0,553.5,82.5,2.4,2.8,22.1,8.0,8 cups,"c(""Preheat oven to 350 degrees."", ""Sautee the ..."

In [15]:
# making one that works in any orther
# work in progress
import re
user_input = input('put your ingridients, followed by a comma')
user_input_list = user_input.split(',')

pattern = r'(?i)\b(?:' + '|'.join(user_input_list) + r')\b'

matched_recipes = recipes.loc[recipes['RecipeInstructions'].str.contains(pattern, flags=re.IGNORECASE, regex = True)]

result_df = pd.DataFrame(matched_recipes, columns = recipes.columns )
styled_df = result_df.style.set_properties(subset=pd.IndexSlice[::2], background='#f5f5f5')

print(styled_df)

put your ingridients, followed by a commacheddar
<pandas.io.formats.style.Styler object at 0x0000017330D0CAF0>

In [16]:
# want to see if my search actually has the ingridients that I searched for 
#in this exampel i searched for garlic and cheddar but pd doesnt let you see the full text


# Store the original option value
original_option = pd.get_option('display.max_colwidth')

# Set display option to show complete text
pd.set_option('display.max_colwidth', None)

print(recipes.loc[recipes['RecipeId'] == 24619, 'RecipeInstructions'])

# Reset the display option to its original value
pd.set_option('display.max_colwidth', original_option)

# After doing this, I can see the search is working

21186    c("Mix sour cream, cottage cheese, about 1/2 the cheddar, garlic, salt, pepper& basil in large mixing bowl.", "Add potatoes and onions, mix well.", "Pour mixture in a 13 by 9 pan that you sprayed with Pam.", "Pat down with the back of your spatula.", "Sprinkle remaining cheese over top.", "In a baggie, crush corn flakes and then add some salt, pepper and garlic powder and toss around a bit.", "Sprinkle corn flake mixture over top of cheese.", "Bake 375 for about an hour.")
Name: RecipeInstructions, dtype: object

In [18]:
recipes.isnull().sum()

RecipeId                           0
Name                               0
AuthorId                           0
AuthorName                         0
CookTime                       82545
PrepTime                           0
TotalTime                          0
DatePublished                      0
Description                        5
Images                             1
RecipeCategory                   751
Keywords                       17237
RecipeIngredientQuantities         3
RecipeIngredientParts              0
AggregatedRating              253223
ReviewCount                   247489
Calories                           0
FatContent                         0
SaturatedFatContent                0
CholesterolContent                 0
SodiumContent                      0
CarbohydrateContent                0
FiberContent                       0
SugarContent                       0
ProteinContent                     0
RecipeServings                182911
RecipeYield                   348071
RecipeInstructions                 0
dtype: int64

In [21]:
reviews.isna().sum()

ReviewId           0
RecipeId           0
AuthorId           0
AuthorName         0
Rating             0
Review           214
DateSubmitted      0
DateModified       0
dtype: int64

In [28]:
recipes.loc[recipes['ReviewCount'].isnull(), ['Name', 'ReviewCount']]
# manually searching it on the website, i can see this ones dont have ANY review
# means 247,489 of this ones dont have review, almost half of the recipes

                                                    Name  ReviewCount
23                                    Brownie Heart Cake          NaN
29                                   Chicago Style Pizza          NaN
30                                        Chicha Peruana          NaN
35                              Brownie Cheesecake Torte          NaN
36                              California Chilled Salsa          NaN
...                                                  ...          ...
522512                    Meg's Fresh Ginger Gingerbread          NaN
522513  Roast Prime Rib au Poivre with Mixed Peppercorns          NaN
522514                             Kirshwasser Ice Cream          NaN
522515          Quick & Easy Asian Cucumber Salmon Rolls          NaN
522516                           Spicy Baked Scotch Eggs          NaN

[247489 rows x 2 columns]

In [30]:
recipes.duplicated().sum()

0

In [31]:
reviews.duplicated().sum()

0

In [ ]:
# classification or predicting can be an option --> lot of nlp analysis
# content based recommended system -> ooking nly at my recipes
# example rating, genre, etc... i could use same of category, ingridients, instructions, reading 'text' on schedule
# runa t least 3 models... 
# clean for now